### delta
GET http://localhost:3003/delta-flights/ABC/DEF

### frontier
POST http://localhost:3002/frontier-flights
Content-Type: application/json

{
    "from": "ABC",
    "to": "XYZ"
}

### jetblue
GET http://localhost:3001/jetblue-flights/ABC/DEF

### agg
GET http://localhost:3000