version: "3.3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: slack
    ports:
      - "5432:5432"

  ws1:
    container_name: ws1
    depends_on:
      - redis
      - db
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - DB_HOST=pg
      - DEBUG=chat-server:*
    build:
      context: ./edge-server
    volumes:
      - ./edge-server:/app

  ws2:
    container_name: ws2
    depends_on:
      - redis
      - db
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - DB_HOST=pg
      - DEBUG=chat-server:*
    build:
      context: ./edge-server
    volumes:
      - ./edge-server:/app
