version: "3.3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
