apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - image: gcr.io/image-upload-352017/myapp:latest
        name: server
        ports:
        - containerPort: 5000
          name: http-server
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: REDIS_URL
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: GOOGLE_CLIENT_SECRET
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: MONGO_URI
        - name: COOKIE_KEY
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: COOKIE_KEY
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: S3_SECRET_ACCESS_KEY_ID
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: NODE_ENV
